language: c

sudo: false

addons:
  postgresql: "9.3"

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec
  - luarocks install https://raw.githubusercontent.com/leafo/lapis/master/lapis-dev-1.rockspec
  - luarocks install moonscript
  - luarocks install luabitop
  - luarocks install date
  - luarocks make

before_script:
  - moonc schema.moon
  - moonc config.moon
  - make clean_test

script: 
  - busted



